import { useEffect, useState } from 'react'
import {
  Brain,
  AlertTriangle,
  Leaf,
  Zap,
  Shield,
  XCircle,
  Loader2,
  RefreshCw,
  Eye,
  EyeOff,
} from 'lucide-react'
import PageHeader from '@/shared/ui/PageHeader'
import { Card } from '@/shared/ui/Card'
import Badge from '@/shared/ui/Badge'
import { api } from '@/shared/utils/api'
import { formatDateTime } from '@/shared/utils/formatters'
import type { AIRecommendationItem } from '@/shared/types/common'

const typeIcons: Record<string, typeof AlertTriangle> = {
  security: Shield,
  carbon: Leaf,
  energy: Zap,
  workload: Brain,
  general: Brain,
}

const typeColorClasses: Record<string, { bg: string; text: string }> = {
  security: { bg: 'bg-danger/10', text: 'text-danger' },
  carbon: { bg: 'bg-success/10', text: 'text-success' },
  energy: { bg: 'bg-accent/10', text: 'text-accent' },
  workload: { bg: 'bg-purple-500/10', text: 'text-purple-400' },
  general: { bg: 'bg-accent/10', text: 'text-accent' },
}

const defaultColorClasses = { bg: 'bg-accent/10', text: 'text-accent' }

const priorityVariant: Record<string, 'danger' | 'warning' | 'primary' | 'muted'> = {
  critical: 'danger',
  high: 'warning',
  medium: 'primary',
  low: 'muted',
}

export default function AiRecommendationsPage() {
  const [recommendations, setRecommendations] = useState<AIRecommendationItem[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [generating, setGenerating] = useState(false)
  const [typeFilter, setTypeFilter] = useState('')
  const [priorityFilter, setPriorityFilter] = useState('')

  const loadRecommendations = async () => {
    try {
      const recs = await api.getRecommendationsList({
        type: typeFilter || undefined,
        priority: priorityFilter || undefined,
      })
      setRecommendations(recs)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    loadRecommendations()
  }, [typeFilter, priorityFilter])

  async function handleGenerate() {
    setGenerating(true)
    try {
      await api.generateRecommendations()
      await loadRecommendations()
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to generate')
    } finally {
      setGenerating(false)
    }
  }

  async function handleMarkRead(id: number) {
    try {
      await api.markRecommendationRead(id)
      setRecommendations((prev) =>
        prev.map((r) => (r.id === id ? { ...r, is_read: true } : r))
      )
    } catch { /* silent */ }
  }

  async function handleDismiss(id: number) {
    try {
      await api.dismissRecommendation(id)
      setRecommendations((prev) => prev.filter((r) => r.id !== id))
    } catch { /* silent */ }
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center h-96">
        <div className="w-10 h-10 border-2 border-border border-t-accent rounded-full animate-spin" />
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <PageHeader
        title="AI Recommendations"
        subtitle="Rule-based security and sustainability recommendations"
        badge={
          <Badge variant="purple" size="sm">
            <span className="inline-block w-1.5 h-1.5 bg-purple-400 rounded-full animate-pulse mr-1" />
            RULE-BASED ENGINE
          </Badge>
        }
        actions={
          <div className="flex gap-2">
            <button
              onClick={() => { setLoading(true); loadRecommendations() }}
              className="flex items-center gap-2 px-3 py-1.5 bg-card border border-border rounded-md text-xs text-muted hover:text-text-primary transition-colors"
            >
              <RefreshCw className="w-3 h-3" />
              Refresh
            </button>
            <button
              onClick={handleGenerate}
              disabled={generating}
              className="flex items-center gap-2 px-4 py-2 bg-purple-500/10 text-purple-400 text-sm font-medium rounded-md hover:bg-purple-500/20 transition-colors disabled:opacity-50"
            >
              {generating ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Brain className="w-4 h-4" />
                  Generate
                </>
              )}
            </button>
          </div>
        }
      />

      {/* Honesty Notice */}
      <Card>
        <div className="flex items-center gap-3">
          <Brain className="w-4 h-4 text-purple-400" />
          <p className="text-xs text-muted">
            Recommendations are generated by a rule-based engine (not machine learning).
            Rules are triggered based on threshold analysis of security events, energy consumption,
            carbon emissions, and renewable energy availability.
          </p>
        </div>
      </Card>

      {error && (
        <Card>
          <div className="flex items-center gap-3 text-danger">
            <AlertTriangle className="w-5 h-5" />
            <p className="text-sm">{error}</p>
          </div>
        </Card>
      )}

      {/* Filters */}
      <Card>
        <div className="flex flex-wrap items-center gap-3">
          <span className="text-xs text-muted font-medium">Filters:</span>
          <select
            value={typeFilter}
            onChange={(e) => setTypeFilter(e.target.value)}
            className="px-3 py-1.5 bg-background border border-border rounded-md text-xs text-text-primary"
          >
            <option value="">All Types</option>
            <option value="security">Security</option>
            <option value="carbon">Carbon</option>
            <option value="energy">Energy</option>
            <option value="workload">Workload</option>
            <option value="general">General</option>
          </select>
          <select
            value={priorityFilter}
            onChange={(e) => setPriorityFilter(e.target.value)}
            className="px-3 py-1.5 bg-background border border-border rounded-md text-xs text-text-primary"
          >
            <option value="">All Priorities</option>
            <option value="critical">Critical</option>
            <option value="high">High</option>
            <option value="medium">Medium</option>
            <option value="low">Low</option>
          </select>
          <span className="text-xs text-muted">{recommendations.length} recommendations</span>
        </div>
      </Card>

      {/* Recommendations List */}
      {recommendations.length === 0 ? (
        <Card>
          <div className="text-center py-12">
            <Brain className="w-8 h-8 text-muted mx-auto mb-2" />
            <p className="text-sm text-muted">No recommendations found</p>
            <p className="text-xs text-muted mt-1">Try generating new recommendations or adjusting filters</p>
          </div>
        </Card>
      ) : (
        <div className="space-y-3">
          {recommendations.map((rec) => {
            const Icon = typeIcons[rec.recommendation_type] || Brain
            const colorCls = typeColorClasses[rec.recommendation_type] || defaultColorClasses
            return (
              <Card key={rec.id} className={rec.is_read ? 'opacity-60' : ''}>
                <div className="flex items-start gap-3">
                  <div className={`p-2 rounded-md ${colorCls.bg} flex-shrink-0 mt-0.5`}>
                    <Icon className={`w-4 h-4 ${colorCls.text}`} />
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1 flex-wrap">
                      <Badge variant={priorityVariant[rec.priority]}>{rec.priority}</Badge>
                      <span className="text-[10px] text-muted uppercase tracking-wider">{rec.recommendation_type}</span>
                      {rec.is_read && (
                        <span className="text-[10px] text-muted">Read</span>
                      )}
                      <span className="text-[10px] text-muted ml-auto">{formatDateTime(rec.timestamp)}</span>
                    </div>
                    <p className="text-sm text-text-primary leading-relaxed">{rec.recommendation}</p>
                    <p className="text-xs text-muted mt-1.5">{rec.reason}</p>
                    <div className="flex items-center gap-4 mt-2">
                      {rec.expected_security_impact && (
                        <span className="text-[10px] text-accent">Security: {rec.expected_security_impact}</span>
                      )}
                      {rec.expected_carbon_impact && (
                        <span className="text-[10px] text-accent-light">Carbon: {rec.expected_carbon_impact}</span>
                      )}
                      <span className="text-[10px] text-muted">{(rec.confidence * 100).toFixed(0)}% confidence</span>
                    </div>
                    <div className="flex items-center gap-2 mt-3">
                      {!rec.is_read && (
                        <button
                          onClick={() => handleMarkRead(rec.id)}
                          className="flex items-center gap-1 px-2 py-1 bg-card border border-border rounded text-[10px] text-muted hover:text-text-primary transition-colors"
                        >
                          <Eye className="w-3 h-3" />
                          Mark Read
                        </button>
                      )}
                      {rec.is_read && (
                        <span className="flex items-center gap-1 px-2 py-1 text-[10px] text-muted">
                          <EyeOff className="w-3 h-3" />
                          Read
                        </span>
                      )}
                      <button
                        onClick={() => handleDismiss(rec.id)}
                        className="flex items-center gap-1 px-2 py-1 bg-card border border-border rounded text-[10px] text-muted hover:text-danger transition-colors"
                      >
                        <XCircle className="w-3 h-3" />
                        Dismiss
                      </button>
                    </div>
                  </div>
                </div>
              </Card>
            )
          })}
        </div>
      )}
    </div>
  )
}
